#!/bin/bash

# Select emoji using fuzzel
emoji=$(cat ~/.config/hypr/scripts/emoji-list.txt | fuzzel --dmenu -p "Emoji: " | awk '{print $1}')

if [ -n "$emoji" ]; then
    sleep 0.1
    wtype "test $emoji test"
fi
