theme = "onedark"

[editor]
bufferline = "multiple"
color-modes = true
popup-border = "all"

[editor.statusline]
center = [ "version-control" ]
right = [ "diagnostics", "selections", "register", "position", "file-encoding", "total-line-numbers" ]

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.whitespace]
render.tab = "all"
