[[language]]
name = "nim"
auto-format = true
indent = { tab-width = 2, unit = " " }

[[language]]
name = "zig"
auto-format = false
indent = { tab-width = 2, unit = " " }

[language-server.superhtml-lsp]
command = "superhtml"
args = ["lsp"]

[[language]]
name = "html"
scope = "source.html"
roots = []
file-types = ["html"]
language-servers = [ "superhtml-lsp" ]
auto-format = true

[[grammar]]
name = "crystal"
source = { git = "https://github.com/crystal-lang-tools/tree-sitter-crystal", rev = "2af0dc12e65b98ea4c9737f645776277ef8d8f55" }

[[language]]
name = "crystal"
scope = "source.crystal" 
file-types = ["cr"]      
roots = ["shard.yml"]    
comment-token = "#"
indent = { tab-width = 2, unit = "  " } 
# grammar = "crystal"
auto-format = true

# Steel
[[language]]
name = "scheme"
formatter = { command = "raco", args = ["fmt", "-i"] }
auto-format = true
language-servers = [ "steel-language-server" ]

# For development
[language-server.steel-language-server]
command = "steel-language-server"
args = []


[language-server.rust-analyzer.config]
experimental = { testExplorer = true }
