#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d I II FLOAT FULL
bspc monitor HDMI-0 -d V VI VII

bspc config border_width         2
bspc config window_gap          12
bspc config focus_follows_pointer   true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Autorun
xrandr --output DP-0 --primary --mode 2560x1440 --pos 0x480 --rotate normal --rate 169.83 --output DP-1 --off --output HDMI-0 --mode 1920x1080 --pos -1080x0 --rotate left --rate 119.98
pipewire &

# /nix/store/$(ls -la /nix/store | grep 'mate-polkit' | grep '4096' | awk '{print $9}' | sed -n '$p')/libexec/polkit-mate-authentication-agent-1 & 
# TODO: playerctld daemon
nitrogen --restore &
dunst &
/usr/libexec/polkit-mate-authentication-agent-1 &
/usr/lib/pam_kwallet_init &
greenclip daemon &
# picom -b &
~/.config/polybar/launch.sh &
thunar --daemon &
