# Halloy config template.
#
# For a complete list of available options,
# please visit https://halloy.squidowl.org/configuration/index.html

theme = "one dark pro"
scale_factor = 1.25

[sidebar]
default_action = "replace-pane"

# [servers.liberachat]
# nickname = "foggy"
# nick_password = "yesno27@"
# alt_nicks = ["foggylight"]
# server = "irc.libera.chat"
# port = 6697
# use_tls = true
# channels = ["#halloy", "#zfsbootmenu", "#voidlinux", "#bnc4free"]

# [servers.liberachat.sasl.plain]
# username = "foggy"
# password = "yesno27@"

[servers.bnc4free]
nickname = "foggy"
nick_password = "yesno27@"
password = "Y3HU4uPExnHQ"
alt_nicks = ["foggylight"]
server = "pear.bnc4free.com"
port = 1339
use_tls = true
channels = ["#halloy", "#zfsbootmenu", "#voidlinux", "#bnc4free"]

[servers.bnc4free.sasl.plain]
username = "foggy"
password = "yesno27@"
